### ISSUE TITLE
[android] package identifier or launch activity not found.

### ISSUE THREAD

**Issue by disonwei** [artcodefun/launcher_icon_switcher#2]
I am using this plugin in an Android project and have configured it according to the instructions. My AndroidManifest is as follows:

‘’‘
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="HabitDone"
        android:name="${applicationName}"
        android:icon="@mipmap/style1_white">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:turnScreenOn="true"
            android:enabled="false"
            >
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        

        <activity-alias
            android:name=".defaultIcon"
            android:icon="@mipmap/default_icon"
            android:enabled="false"
            android:exported="true"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity-alias>

        <activity-alias
            android:name=".iconBlackWhite"
            android:icon="@mipmap/icon_black_white"
            android:enabled="true"
            android:exported="true"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity-alias>

’‘’

After running 'flutter clean', I encounter errors when running 'flutter run'：

package identifier or launch activity not found.
Please check /Users/dison/dison/project/HabitDone/HabitDone_Flutter/android/app/src/main/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.

I must set android:enabled="true" in the activity in order to build the project successfully.
After successfully building the project, if I modify the code as mentioned above without running 'flutter clean' and directly run 'flutter run', the build is successful. Why does this happen?

**Comment by artcodefun** [comment]
Hi, @disonwei !
So, there is a known [issue](https://github.com/flutter/flutter/issues/38965) with `flutter run` when used with `activity-alias`
This is specifically the problem of `flutter run` command, but if you try building your project first with `flutter build apk --debug`, there should be no problem executing `flutter run`

**Comment by disonwei** [comment]
Thank you for your answer! @artcodefun
