### ISSUE TITLE
App appears twice in Android drawer

### ISSUE THREAD

**Issue by maxfornacon** [artcodefun/launcher_icon_switcher#6]
I followed the instructions to setup the package for android. 

When I select the new icon the app restarts, as shown in the gif you provided, but the icon is not changed on my home screen. Instead there is a second entry of my app in my app drawer with one showing the new icon and one showing the default one. 

I'm using android 12 on my device.

**Comment by artcodefun** [comment]
Hi, @maxfornacon !
This behavior can occur, for example, if you keep your main activity enabled along with some alias. Are you sure that the only enabled element in your AndroidManifest.xml is a default `activity-alias`?

**Comment by maxfornacon** [comment]
> Are you sure that the only enabled element in your AndroidManifest.xml is a default activity-alias?

I forgot to explicitly set `android:enabled=false`. Thank you!
